package com.example.simpleqrbarcodescanner_noads.Util

object Intent_KEYS {
    const val QRCODE = "qrCode"
    const val FORMAT = "format"
    const val VALUETYPE = "valuetype"
    const val BUNDLE = "Bundle"

    val URL = "URL"
    val WIFINAME = "WIFINAME"
    val PASSWORD = "PASSWORD"
    val ENCRYPTION_VALUE = "ENCRYPTION_TYPE"
    val EMAIL_ADDRESS = "EMAIL_ADDRESS"
    val EMAIL_SUBJECT = "EMAIL_SUBJECT"
    val EMAIL_BODY = "EMAIL_BODY"
    val SMS_PHONE = "SMS_PHONE"
    val MESSAGE = "MESSAGE"

    val LICENCE_NUMBER = "LICENCE_NUMBER"
    val LICENCE_FIRSTNAME = "LICENCE_FIRSTNAME"
    val LICENCE_MIDDLENAME = "LICENCE_MIDDLENAME"
    val LICENCE_LASTNAME = "LICENCE_LASTNAME"
    val LICENCE_DOB = "LICENCE_DOB"
    val LICENCE_EXPDATE = "LICENCE_EXPDATE"
    val LICENCE_ISSUEDATE = "LICENCE_ISSUEDATE"
    val LICENCE_DOCTYPE = "LICENCE_DOCTYPE"
    val LICENCE_GENDER = "LICENCE_GENDER"
    val LICENCE_ISSUCOUNTRY = "LICENCE_ISSUCOUNTRY"
    val LICENCE_ADSTREET = "LICENCE_ADSTREET"
    val LICENCE_ADSTATE = "LICENCE_ADSTATE"
    val LICENCE_ADCITY = "LICENCE_ADCITY"
    val LICENCE_ADZIP = "LICENCE_ADZIP"

    val VOID = "VOID"
}